### ISSUE TITLE
Blackout/Artificiallights sets the Deadline effects black

### ISSUE THREAD

**Issue by VIRUXE** [TomGrobbe/Tron#2]
Maybe I'm doing something wrong. Tried changing the primary and secondary colors via vMenu and still no result.
![image](https://user-images.githubusercontent.com/1616657/118144571-84741100-b404-11eb-8b88-c71c6c30f63a.png)

**Comment by HearingSubset19** [comment]
Pretty sure he said that does nothing. don't quote me on it thought

Features
The trail color is based on the vehicle color combination. Custom paint’s won’t work, you have to use vehicle color combinations.
Trail disappears when you get off your bike.

**Comment by VIRUXE** [comment]
@HearingSubset19 I read that. It's a simple `CreateVehicle(vehicleName, pos.x, pos.y, pos.z, GetEntityHeading(playerPed), true, false)`

**Comment by TomGrobbe** [comment]
Black shouldn't even be an option, so I'm guessing you're using a graphics mod that doesn't support colored sprite poly's.

**Comment by HearingSubset19** [comment]
Because mine matches the Tron color

**Comment by HearingSubset19** [comment]
~~Nope, stock~~ didn't read who sent it my bad

**Comment by TomGrobbe** [comment]
> Nope, stock

What's stock?

**Comment by HearingSubset19** [comment]
> > Nope, stock
> 
> What's stock?

Disregard I thought he was talking about me not having a resource pack. But I didn't read the name so I though it was the person asking me didn't realize it was sir pizza master 🍕

**Comment by VIRUXE** [comment]
@TomGrobbe Clean installation. Maybe SetBlackout has something to do with it?

**Comment by TomGrobbe** [comment]
> @TomGrobbe Clean installation. Maybe SetBlackout has something to do with it?

Maybe. I've not tested that. Are you sure the server doesn't have _any_ graphics related resources enabled? Though limited, servers have some options to stream graphics mods. They don't have to always be installed on the client side.

**Comment by VIRUXE** [comment]
![image](https://user-images.githubusercontent.com/1616657/118365197-989a4880-b593-11eb-8c93-d898cc02357c.png)
I'll disable blackout and see how it goes.

**Comment by TomGrobbe** [comment]
I've tested it with artificial lights disabled, and that causes the trail to be black. So turn off 'blackout' and you should be fine.
